In [1]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib as plt

In [11]:
#loading the dataset
data = pd.read_csv('/content/drive/MyDrive/samplesuperstore.csv')

#display first 5 rows
data.head().transpose()

,0,1,2,3,4
Row ID,1,2,3,4,5
Order ID,US-2023-103800,US-2023-112326,US-2023-112326,US-2023-112326,US-2023-141817
Order Date,1/3/2023,1/4/2023,1/4/2023,1/4/2023,1/5/2023
Ship Date,1/7/2023,1/8/2023,1/8/2023,1/8/2023,1/12/2023
Ship Mode,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class
Customer ID,DP-13000,PO-19195,PO-19195,PO-19195,MB-18085
Customer Name,Darren Powers,Phillina Ober,Phillina Ober,Phillina Ober,Mick Brown
Segment,Consumer,Home Office,Home Office,Home Office,Consumer
Country/Region,United States,United States,United States,United States,United States
City,Houston,Naperville,Naperville,Naperville,Philadelphia
State/Province,Texas,Illinois,Illinois,Illinois,Pennsylvania
Postal Code,77095,60540,60540,60540,19143
Region,Central,Central,Central,Central,East
Product ID,OFF-PA-10000174,OFF-BI-10004094,OFF-LA-10003223,OFF-ST-10002743,OFF-AR-10003478
Category,Office Supplies,Office Supplies,Office Supplies,Office Supplies,Office Supplies
Sub-Category,Paper,Binders,Labels,Storage,Art
Product Name,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",GBC Standard Plastic Binding Systems Combs,Avery 508,SAFCO Boltless Steel Shelving,Avery Hi-Liter EverBold Pen Style Fluorescent ...
Sales,16.448,3.54,11.784,272.736,19.536
Quantity,2,2,3,3,3
Discount,0.2,0.8,0.2,0.2,0.2
Profit,5.5512,-5.487,4.2717,-64.7748,4.884

In [12]:
# number of rows and columns
data.shape

(10194, 21)

In [13]:
#column types
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   Country/Region  10194 non-null  object
 9   City            10194 non-null  object
 10  State/Province  10194 non-null  object
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  object
 13  Product ID      10194 non-null  object
 14  Category        10194 non-null  object
 15  Sub-Category    10194 non-null  object
 16  Product Name    10194 non-null  object
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: float64(3), int64(2), object(16)
memory usage: 1.6+ MB

In [14]:
#sum of nulls
data.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [15]:
#count duplicates
data.duplicated().sum()

np.int64(0)

In [16]:
#drop unique identifiers
data.drop(columns=['Row ID', 'Order ID', 'Customer ID'], inplace=True)
print(data.columns)

Index(['Order Date', 'Ship Date', 'Ship Mode', 'Customer Name', 'Segment',
       'Country/Region', 'City', 'State/Province', 'Postal Code', 'Region',
       'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales',
       'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [17]:
#change data type to datetime
data['Order Date'] = pd.to_datetime(data['Order Date'])

In [18]:
#change data type to date type
data['Ship Date'] = pd.to_datetime(data['Ship Date'])
data['Month'] = data['Order Date'].dt.to_period('M')

In [20]:
#save the cleaned dataset
data.to_csv('super_store_sales.csv', index=False)